// <auto-generated />
namespace FilmSite.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updt));
        
        string IMigrationMetadata.Id
        {
            get { return "201706180921054_updt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
